/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as DeepRouteImport } from './routes/deep'
import { Route as ChroniclesRouteImport } from './routes/chronicles'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepRoute = DeepRouteImport.update({
  id: '/deep',
  path: '/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ChroniclesRoute = ChroniclesRouteImport.update({
  id: '/chronicles',
  path: '/chronicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicles': typeof ChroniclesRoute
  '/deep': typeof DeepRoute
  '/habits': typeof HabitsRoute
  '/matrix': typeof MatrixRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicles': typeof ChroniclesRoute
  '/deep': typeof DeepRoute
  '/habits': typeof HabitsRoute
  '/matrix': typeof MatrixRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicles': typeof ChroniclesRoute
  '/deep': typeof DeepRoute
  '/habits': typeof HabitsRoute
  '/matrix': typeof MatrixRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/chronicles'
    | '/deep'
    | '/habits'
    | '/matrix'
    | '/recovery'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/chronicles'
    | '/deep'
    | '/habits'
    | '/matrix'
    | '/recovery'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/chronicles'
    | '/deep'
    | '/habits'
    | '/matrix'
    | '/recovery'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChroniclesRoute: typeof ChroniclesRoute
  DeepRoute: typeof DeepRoute
  HabitsRoute: typeof HabitsRoute
  MatrixRoute: typeof MatrixRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep': {
      id: '/deep'
      path: '/deep'
      fullPath: '/deep'
      preLoaderRoute: typeof DeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicles': {
      id: '/chronicles'
      path: '/chronicles'
      fullPath: '/chronicles'
      preLoaderRoute: typeof ChroniclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChroniclesRoute: ChroniclesRoute,
  DeepRoute: DeepRoute,
  HabitsRoute: HabitsRoute,
  MatrixRoute: MatrixRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
